# Generated by Django 5.1.2 on 2024-10-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentid', models.CharField(max_length=20)),
                ('consignee', models.CharField(max_length=200)),
                ('ata', models.CharField(max_length=50)),
                ('cargoavailable', models.CharField(max_length=50)),
                ('datecleared', models.CharField(max_length=50)),
                ('actualdelivery', models.CharField(max_length=50)),
                ('cont', models.CharField(max_length=10)),
                ('twentyft', models.CharField(max_length=10)),
                ('fortyft', models.CharField(max_length=10)),
                ('uw', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
            ],
        ),
    ]
