# Generated by Django 5.1.2 on 2025-03-17 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('vendor', models.CharField(max_length=200)),
                ('po_number', models.CharField(max_length=200)),
                ('driver_name', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('place_of_loading', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('fuel_quantity', models.CharField(max_length=50)),
                ('initial_tank_amount', models.CharField(max_length=100)),
                ('top_up_quantity', models.CharField(max_length=100)),
                ('authorized_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='transport_mode',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
