# Generated by Django 5.1.2 on 2024-10-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='actualdelivery',
            new_name='actual_delivery',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='cargoavailable',
            new_name='cargo_available',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='datecleared',
            new_name='date_cleared',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='fortyft',
            new_name='forty_ft',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='shipmentid',
            new_name='shipment_id',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='twentyft',
            new_name='twenty_ft',
        ),
    ]
