# Generated by Django 5.1.2 on 2025-05-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('booking_req', models.DateField(max_length=50)),
                ('transport_ref', models.CharField(max_length=50)),
                ('booking_id', models.CharField(max_length=50)),
                ('parent_id', models.CharField(max_length=50)),
                ('first_pick_up_name', models.CharField(max_length=50)),
                ('first_pic_equipment', models.CharField(max_length=50)),
                ('first_pic_actual', models.DateField(max_length=50)),
                ('first_pic_city', models.CharField(max_length=50)),
                ('last_del_act', models.DateField(max_length=50)),
                ('last_del_city', models.CharField(max_length=50)),
                ('hazardous', models.CharField(max_length=50)),
                ('goods_description', models.CharField(max_length=50)),
                ('chargeable_wgt', models.DecimalField(decimal_places=2, max_digits=20)),
                ('chargeable_wgt_unit', models.CharField(max_length=50)),
                ('transport', models.CharField(max_length=50)),
                ('first_pic_up_cont_mode', models.CharField(max_length=50)),
                ('first_pu_cont_type', models.CharField(max_length=50)),
                ('consignee_package_qty', models.IntegerField()),
                ('first_pu_pkg_type', models.CharField(max_length=50)),
            ],
        ),
    ]
