# Generated by Django 5.1.2 on 2025-03-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pretrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('odometer_start', models.CharField(max_length=100)),
                ('odometer_end', models.CharField(max_length=100)),
                ('fuel_start', models.CharField(max_length=100)),
                ('fuel_end', models.CharField(max_length=100)),
                ('fuel_used', models.CharField(max_length=100)),
                ('fuel_cost', models.CharField(max_length=100)),
                ('driver_signature', models.CharField(max_length=100)),
                ('supervisor_signature', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
