# Generated by Django 5.1.2 on 2025-03-17 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0002_fuelreq_shipment_transport_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelreq',
            name='signature',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelreq',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fuelreq',
            name='driver_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fuelreq',
            name='fuel_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelreq',
            name='initial_tank_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelreq',
            name='po_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fuelreq',
            name='top_up_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuelreq',
            name='vendor',
            field=models.CharField(max_length=100),
        ),
    ]
