# Generated by Django 5.1.2 on 2025-06-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0003_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': [('can_view_page', 'View Page'), ('can_view_page_ops', 'View Ops Page'), ('can_view_page_finance', 'View Finance Page'), ('can_view_page_qhse', 'View QHSE Page'), ('can_view_page_hr_support', 'View HR Page')]},
        ),
    ]
