# Generated by Django 5.1.2 on 2025-07-11 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0004_alter_contact_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelreq',
            name='signature',
        ),
        migrations.AddField(
            model_name='fuelreq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelreq',
            name='driver_phone',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelreq',
            name='driver_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelreq',
            name='signature_data_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelreq',
            name='signed_by_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fuelreq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fuelreq',
            name='po_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fuelreq',
            name='vehicle_number',
            field=models.CharField(max_length=50),
        ),
    ]
