# Generated by Django 5.1.2 on 2024-10-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0005_alter_shipment_ata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='actual_delivery',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cargo_available',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cont',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date_cleared',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='forty_ft',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='twenty_ft',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='uw',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.IntegerField(max_length=10),
        ),
    ]
