# Generated by Django 5.1.2 on 2024-10-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0006_alter_shipment_actual_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='forty_ft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='twenty_ft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
