# Generated by Django 5.1.2 on 2025-07-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0006_category_employee_company_employee_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
