# Generated by Django 5.1.2 on 2024-10-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0007_alter_shipment_forty_ft_alter_shipment_twenty_ft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='cont',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='forty_ft',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='twenty_ft',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='uw',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.CharField(),
        ),
    ]
