# Generated by Django 5.1.2 on 2024-10-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0008_alter_shipment_cont_alter_shipment_forty_ft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.CharField(max_length=15),
        ),
    ]
