# Generated by Django 5.1.2 on 2024-10-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0010_alter_shipment_actual_delivery_alter_shipment_ata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='actual_delivery',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ata',
            field=models.DateField(max_length=15),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cargo_available',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date_cleared',
            field=models.DateField(max_length=20),
        ),
    ]
