# Generated by Django 5.1.2 on 2024-11-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0011_alter_shipment_actual_delivery_alter_shipment_ata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
