# Generated by Django 5.1.2 on 2024-11-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0013_delete_category_alter_shipment_actual_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('can_view_page', 'View Page'),),
            },
        ),
    ]
