# Generated by Django 5.1.2 on 2024-11-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0014_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': (('can_view_page2', 'View Page'),)},
        ),
    ]
