# Generated by Django 5.1.2 on 2024-11-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0018_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': [('can_view_page', 'View Page'), ('can_view_page_ops', 'View Ops Page'), ('can_view_page_finance', 'View Finance Page'), ('can_view_page_qhse', 'View QHSE Page'), ('can_view_page_hr', 'View HR Page')]},
        ),
    ]
