# Generated by Django 5.1.2 on 2024-11-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0019_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50)),
                ('parent_id', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('booking_req', models.CharField(max_length=50)),
                ('first_pic_actual', models.CharField(max_length=50)),
                ('first_pic_city', models.CharField(max_length=50)),
                ('last_del_act', models.CharField(max_length=50)),
                ('last_del_city', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('hazardous', models.CharField(max_length=50)),
                ('goods_description', models.CharField(max_length=50)),
                ('chargeable_wgt', models.CharField(max_length=50)),
                ('chargeable_wgt_unit', models.CharField(max_length=50)),
                ('transport', models.CharField(max_length=50)),
                ('first_pic_equipment', models.CharField(max_length=50)),
                ('first_pickup_instructions', models.CharField(max_length=50)),
                ('first_pu_pkg_cont_id', models.CharField(max_length=50)),
                ('first_pick_up_cont_mode', models.CharField(max_length=50)),
                ('first_pu_cont_type', models.CharField(max_length=50)),
                ('consignee_package_qty', models.CharField(max_length=50)),
                ('first_pu_pkg_qty', models.CharField(max_length=50)),
                ('first_pu_pkg_type', models.CharField(max_length=50)),
                ('first_pickup_name', models.CharField(max_length=50)),
                ('booked_by', models.CharField(max_length=50)),
            ],
        ),
    ]
