# Generated by Django 5.1.2 on 2024-12-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0022_transport_first_pu_pkg_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.IntegerField(max_length=50),
        ),
    ]
