# Generated by Django 5.1.2 on 2024-12-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0023_alter_shipment_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.CharField(max_length=50),
        ),
    ]
