# Generated by Django 5.1.2 on 2024-12-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0024_alter_shipment_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.CharField(max_length=15),
        ),
    ]
