# Generated by Django 5.1.2 on 2024-12-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0025_alter_shipment_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_number', models.CharField(max_length=50)),
                ('shipper', models.CharField(max_length=50)),
                ('consignee', models.CharField(max_length=50)),
                ('notify_party', models.CharField(max_length=50)),
                ('vessel', models.CharField(max_length=50)),
                ('port_of_loading', models.CharField(max_length=50)),
                ('port_of_discharge', models.CharField(max_length=50)),
                ('container_quantity1', models.CharField(max_length=50)),
                ('container_type1', models.CharField(max_length=50)),
                ('container_quantity2', models.CharField(max_length=50)),
                ('container_type2', models.CharField(max_length=50)),
                ('package_quantity1', models.CharField(max_length=50)),
                ('package_type1', models.CharField(max_length=50)),
                ('package_quantity2', models.CharField(max_length=50)),
                ('package_type2', models.CharField(max_length=50)),
                ('kg_weight', models.CharField(max_length=50)),
                ('m3', models.CharField(max_length=50)),
                ('container_number', models.CharField(max_length=50)),
            ],
        ),
    ]
