# Generated by Django 5.1.2 on 2024-12-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0027_alter_bill_bl_number_alter_bill_consignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='container_quantity1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='container_quantity2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='kg_weight',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='m3',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='package_quantity1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='package_quantity2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='forty_ft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='twenty_ft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transport',
            name='chargeable_wgt',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transport',
            name='consignee_package_qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transport',
            name='first_pic_actual',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transport',
            name='last_del_act',
            field=models.DateField(max_length=50),
        ),
    ]
