# Generated by Django 5.1.2 on 2025-01-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0029_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=20)),
                ('client', models.CharField(max_length=100)),
                ('client_po_number', models.CharField(max_length=20)),
                ('invoice_date', models.DateField(max_length=30)),
                ('currency', models.DecimalField(decimal_places=2, max_digits=20)),
                ('goods_description', models.CharField(max_length=200)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('price_unit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('incoterms', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
