# Generated by Django 5.1.2 on 2025-01-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0031_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=20)),
                ('client', models.CharField(max_length=100)),
                ('client_po_number', models.CharField(max_length=20)),
                ('pack_date', models.DateField(max_length=30)),
                ('goods_description', models.CharField(max_length=200)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('hscode', models.CharField(max_length=50)),
            ],
        ),
    ]
