# Generated by Django 5.1.2 on 2025-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_board', '0032_packlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packlist',
            name='client',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='packlist',
            name='goods_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='packlist',
            name='hscode',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='packlist',
            name='pack_date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='packlist',
            name='vendor',
            field=models.CharField(max_length=50),
        ),
    ]
